version: '3'

services:
  start-petclinic-tests:
    image: pet-auto-tests:latest
    environment:
      - DpetclinicUrl=spring-petclinic-sample:8080
      - DadminUrl=drill-admin:8090
      - DagentId=dev-pet-standalone
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
