version: '3'

services:
  start-petclinic-tests:
    image: drill4j/petclinic-autotests-execute:latest
    environment:
      - petclinicUrl=http://host.docker.internal:8087
      - adminHost=host.docker.internal
      - adminPort=9090
      - agentId=dev-pet-standalone
